- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .lighthouse/jenkins-x/release.yaml
- .lighthouse/jenkins-x/triggers.yaml
- postgres/conf/usr/bin/run-postgresql
- postgres/conf/usr/share/container-scripts/postgresql/common.sh
> fix(ansible-docker-ci): add coreutils for basename bin 

- .ansible-ci/files/templated_contexts/base/conf/usr/bin/container-entrypoint
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/nginx/conf/container-entrypoint.d/nginx-entrypoint
- .ansible-ci/files/templated_contexts/php-fpm/conf/container-entrypoint.d/php-fpm-entrypoint
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/platform/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_nginx_web/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_php-fpm/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_web/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/nginx_php-fpm/dockerfile_builder.yml
- .ansible-ci/tasks/build.yml
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> ci: fix pipelines format

- .ansible-ci/files/templated_contexts/php-fpm/conf/container-entrypoint.d/php-fpm.env
- .ansible-ci/files/templated_contexts/php-fpm/conf/usr/bin/container-setup-php
- .ansible-ci/inventory/host_vars/ansible/dockerfile_builder.yml
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> feat(php-fpm): add variable for process control timeout

- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/base/conf/usr/bin/timezone-set
- .ansible-ci/files/templated_contexts/centos8-stream-minimal/centos8-stream-minimal.ks
- .ansible-ci/files/templated_contexts/moodle_app/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/check-container-php
- .ansible-ci/inventory/group_vars/m4e/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_app/dockerfile_builder.yml
- .ansible-ci/tasks/prepare/moodle.yml
> feat(moodle): add option to export moodle status to json

- .ansible-ci/files/templated_contexts/nginx/Dockerfile.j2
- .ansible-ci/files/templated_contexts/nginx/conf/usr/bin/container-setup-nginx
- .ansible-ci/files/templated_contexts/php-fpm/conf/usr/bin/container-setup-php
> some fixes

- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
> build(ansible-operator-ci): bump kustomize version

- .ansible-ci/files/templated_contexts/ansible-operator-ci/Dockerfile.j2
- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
> build(ansible-operator): bump kubectl version

- .ansible-ci/files/templated_contexts/ansible-operator-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/centos8-minimal/centos8-minimal.ks
- .ansible-ci/files/templated_contexts/centos8-stream-minimal/centos8-stream-minimal.ks
- .ansible-ci/files/templated_contexts/rootfs-creator/Dockerfile.j2
- .ansible-ci/files/templated_contexts/rootfs-creator/conf/usr/bin/rootfs-creator
- .ansible-ci/inventory/host_vars/rootfs-creator/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
- .ansible-ci/tasks/prepare/centos8.yml
- .ansible-ci/vars/ci.yml
- .github/ISSUE_TEMPLATE/enhancement_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-and-qa.md
- .lighthouse/jenkins-x/triggers.yaml
> fix(rootfs-creator): do not use xfs filesystem 

- .ansible-ci/files/templated_contexts/rocky8-minimal/Dockerfile.j2
- .ansible-ci/files/templated_contexts/rocky8-minimal/README.md.j2
- .ansible-ci/files/templated_contexts/rocky8-minimal/rocky8-minimal.ks
- .ansible-ci/inventory/hosts
- .ansible-ci/tasks/prepare/centos8.yml
- .gitignore
> feat: add rocky linux minimal container

- .ansible-ci/inventory/host_vars/base/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_app/dockerfile_builder.yml
> feat: use Rocky Linux minimal container for base image

- .ansible-ci/files/templated_contexts/ansible-operator-ci/README.md.j2
- .ansible-ci/files/templated_contexts/ansible-podman-ci/README.md.j2
- .ansible-ci/files/templated_contexts/ansible/README.md.j2
- .ansible-ci/files/templated_contexts/base/README.md.j2
- .ansible-ci/files/templated_contexts/httpd/README.md.j2
- .ansible-ci/files/templated_contexts/moodle_app/README.md.j2
- .ansible-ci/files/templated_contexts/moodle_httpd/README.md.j2
- .ansible-ci/files/templated_contexts/moodle_nginx/README.md.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/README.md.j2
- .ansible-ci/files/templated_contexts/nginx/README.md.j2
- .ansible-ci/files/templated_contexts/php-fpm/README.md.j2
- .ansible-ci/files/templated_contexts/postgres/README.md.j2
- .ansible-ci/files/templated_contexts/rootfs-creator/README.md.j2
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> refactor: moodle app

- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/release.yml
- .ansible-ci/tasks/doc.yml
- .ansible-ci/tasks/updatebot.yml
- .ansible-ci/templates/README.md.j2
- .ansible-ci/templates/updatebot-m4e.yaml.j2
- .ansible-ci/vars/pipeline/release.yml
- .lighthouse/jenkins-x/release.yaml
- .lighthouse/updatebot-m4e.yaml
> feat: add updatebot for downstream repo

- .ansible-ci/inventory/host_vars/postgres/dockerfile_builder.yml
- .ansible-ci/templates/updatebot-m4e.yaml.j2
> cii: use image digest for updatebot 

- .ansible-ci/templates/updatebot-m4e.yaml.j2
> fix: change updatebot image

- .ansible-ci/files/templated_contexts/go-toolset/Dockerfile.j2
- .ansible-ci/files/templated_contexts/go-toolset/README.md.j2
- .ansible-ci/files/templated_contexts/moodle_app/version.json
- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/go-toolset/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
> chore(ansible-operator-ci): bump operator sdk and kubectl versions

- .ansible-ci/files/templated_contexts/base/Dockerfile.j2
- .ansible-ci/files/templated_contexts/httpd/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_app/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_httpd/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_nginx/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/bin/container-setup-php-moodle
- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/moodle/reset-user-pass.php
- .ansible-ci/files/templated_contexts/nginx/Dockerfile.j2
- .ansible-ci/files/templated_contexts/php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/postgres/Dockerfile.j2
- .ansible-ci/files/templated_contexts/rootfs-creator/Dockerfile.j2
> feat(moodle_php-fpm): include reset user pass script

- .ansible-ci/templates/updatebot-m4e.yaml.j2
> ci: add nginx image to updatebot

- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
> chore(ansible-operator-ci): upgrade 1.9.0 to 1.11.0

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/container-entrypoint.d/php-moodle-entrypoint
- .ansible-ci/inventory/host_vars/go-toolset/dockerfile_builder.yml
> refactor(moodle_web): adjust config.php permissions

- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
> chore(ansible-operator-ci): bump operator

- .ansible-ci/files/templated_contexts/keydb/Dockerfile.j2
- .ansible-ci/files/templated_contexts/keydb/README.md.j2
- .ansible-ci/files/templated_contexts/keydb/conf/usr/bin/container-setup-keydb
- .ansible-ci/inventory/group_vars/platform/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/keydb/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
> feat(keydb): init image

- .ansible-ci/inventory/host_vars/keydb/dockerfile_builder.yml
> refactor(keydb): use keydb version for tagging

- .ansible-ci/files/templated_contexts/node/Dockerfile.j2
- .ansible-ci/files/templated_contexts/node/README.md.j2
- .ansible-ci/inventory/group_vars/platform/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/node/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
> feat(node): add container image

- .ansible-ci/files/templated_contexts/node/Dockerfile.j2
> feat(node): add make pckg

- .ansible-ci/files/templated_contexts/node-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/node-ci/README.md.j2
- .ansible-ci/files/templated_contexts/node/Dockerfile.j2
- .ansible-ci/inventory/group_vars/node/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/node-ci/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/node/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
> feat(node-ci): add node image for CI and building node apps

- .ansible-ci/files/templated_contexts/moodle_nginx/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_nginx/README.md.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/README.md.j2
- .ansible-ci/files/templated_contexts/php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/php-fpm/README.md.j2
- .ansible-ci/inventory/group_vars/m4e/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_nginx_web/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_web/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/nginx_php-fpm/dockerfile_builder.yml
> wip: fix: only install phpredis in one container image

- .ansible-ci/files/templated_contexts/moodle_nginx/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/README.md.j2
- .ansible-ci/files/templated_contexts/nginx/README.md.j2
- .ansible-ci/files/templated_contexts/php-fpm/Dockerfile.j2
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/m4e/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle_web/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
> refactor: set image basic env var as default

- .ansible-ci/files/templated_contexts/postgres/Dockerfile.j2
- .ansible-ci/files/templated_contexts/postgres/conf/usr/bin/run-postgresql-master
- .ansible-ci/files/templated_contexts/postgres/conf/usr/bin/run-postgresql-slave
> refactor(postgres): set replication var in read or primary scripts

- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/nfs-ganesha/Dockerfile.j2
- .ansible-ci/files/templated_contexts/nfs-ganesha/README.md.j2
- .ansible-ci/files/templated_contexts/nfs-ganesha/conf/container-entrypoint.d/nfs-ganesha-entrypoint
- .ansible-ci/files/templated_contexts/nfs-ganesha/conf/usr/bin/container-setup-nfs-ganesha
- .ansible-ci/files/templated_contexts/nginx/conf/usr/bin/container-setup-nginx
- .ansible-ci/files/templated_contexts/pgbouncer/conf/usr/bin/container-setup-pgbouncer
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/m4e/dockerfile_builder.yml
- .ansible-ci/inventory/hosts
> feat: add nfs ganesha server

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/check-container-php
> feat(moodle): handle check during upgrade

- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
> feat: bump nginx to stable version 1.20

- .ansible-ci/build.yml
- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/ansible-operator-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/ansible-podman-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/graphql-engine/Dockerfile.j2
- .ansible-ci/files/templated_contexts/keydb/conf/usr/bin/container-setup-keydb
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/all/terraform.yml
- .ansible-ci/inventory/group_vars/ci/dockerfile_builder.yml
- .ansible-ci/library/terraform.py
- .ansible-ci/multiarch-builder.yml
- .ansible-ci/tasks/build.yml
- .ansible-ci/tasks/builder/cache.yml
- .ansible-ci/tasks/prepare/ansible-ci.yml
- .ansible-ci/tasks/prepare/centos8.yml
- .ansible-ci/tasks/terraform-module.yml
- .ansible-ci/vars/main.yml
- .gitignore
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> Use remote multiarch builders

- .ansible-ci/build.yml
- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/ansible-operator-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/ansible-podman-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/graphql-engine/Dockerfile.j2
- .ansible-ci/files/templated_contexts/keydb/conf/usr/bin/container-setup-keydb
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/all/terraform.yml
- .ansible-ci/inventory/group_vars/ci/dockerfile_builder.yml
- .ansible-ci/library/terraform.py
- .ansible-ci/multiarch-builder.yml
- .ansible-ci/tasks/build.yml
- .ansible-ci/tasks/builder/cache.yml
- .ansible-ci/tasks/prepare/ansible-ci.yml
- .ansible-ci/tasks/prepare/centos8.yml
- .ansible-ci/tasks/terraform-module.yml
- .ansible-ci/vars/main.yml
- .gitignore
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> feat: add multiarch builders

- .ansible-ci/files/templated_contexts/go-toolset/Dockerfile.j2
- .ansible-ci/files/templated_contexts/httpd/Dockerfile.j2
- .ansible-ci/files/templated_contexts/httpd/conf/usr/bin/container-setup-httpd
- .ansible-ci/files/templated_contexts/nfs-ganesha/conf/usr/bin/container-setup-nfs-ganesha
- .ansible-ci/files/templated_contexts/nginx/conf/usr/bin/container-setup-nginx.j2
- .ansible-ci/files/templated_contexts/node/Dockerfile.j2
- .ansible-ci/files/templated_contexts/php-fpm/conf/usr/bin/container-setup-php.j2
- .ansible-ci/files/templated_contexts/postgres/conf/usr/bin/container-setup-postgres.j2
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/graphql_engine/dockerfile_builder.yml
- .ansible-ci/inventory/group_vars/node/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/go118-toolset/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/nginx120_php80-fpm/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/node14-ci/dockerfile_builder.yml
- .ansible-ci/tasks/builder/version.yml
- .ansible-ci/tasks/promote/copy.yml
- .ansible-ci/tasks/promote/main.yml
- .ansible-ci/tasks/state/load.yml
- .ansible-ci/templates/CTR-REPO-README.md.j2
- .ansible-ci/templates/README.md.j2
- .ansible-ci/templates/state.yml.j2
- .ansible-ci/vars/pipeline/build.yml
- .ansible-ci/vars/state/ansible-docker-ci.yml
- .ansible-ci/vars/state/ansible-operator-ci.yml
- .ansible-ci/vars/state/ansible-podman-ci.yml
- .ansible-ci/vars/state/ansible.yml
- .ansible-ci/vars/state/pgbouncer.yml
> refactor: adjust ctr tags

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/container-entrypoint.d/php-moodle-entrypoint
> fix(moodle): update entrypoint script

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/container-entrypoint.d/php-moodle-entrypoint
> fix(moodle): add moodle php ini

- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/container-entrypoint.d/php-moodle-entrypoint
- .ansible-ci/files/templated_contexts/pgbouncer/conf/container-entrypoint.d/pgbouncer.env
- .ansible-ci/tasks/prepare/base.yml
- .ansible-ci/tasks/prepare/minimal.yml
> feat: add read permissions to moodledata

- .ansible-ci/files/templated_contexts/keydb/Dockerfile.j2
- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
- .ansible-ci/tasks/config/buildx/k8s.yml
- .ansible-ci/tasks/config/docker.yml
- .ansible-ci/tasks/prepare/minimal.yml
- .ansible-ci/vars/provider/kio.yml
- .lighthouse/jenkins-x/pullrequest.yaml
- .lighthouse/jenkins-x/release.yaml
> ci: use kio multiarch-builder

- .ansible-ci/files/templated_contexts/base/conf/usr/bin/install-pkgs
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/inventory/group_vars/moodle41_grp/dockerfile_builder.yml
> feat(moodle): update pkgs 

- .ansible-ci/vars/pipeline/release.yml
> fix(release): do not apply docker config tasks

- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/moodle_php-fpm/Dockerfile.j2
- .ansible-ci/inventory/group_vars/moodle/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle41/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle41/readme.yml
- .ansible-ci/inventory/host_vars/moodle41_bundle/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle41_kio/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle41_kio/readme.yml
- .ansible-ci/inventory/hosts
- .ansible-ci/tasks/prepare/moodle-kio.yml
- .ansible-ci/vars/pipeline/release.yml
- .ansible-ci/vars/provider/kio.yml
> fix(moodle): set moodle commit

- .ansible-ci/files/templated_contexts/base/conf/container-entrypoint.d/cgroup-limits.env
> feat(base): detect memory and cpu limits for cgroup v2

- .ansible-ci/files/templated_contexts/moodle_nginx/conf/usr/libexec/check-container-nginx-moodle
- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/check-container-php-moodle
> fix(moodle): omit unix socket

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/check-container-php-moodle
add database socket check
**Checklist:**
> fix(moodle): reduce php moodle check overhead

- .ansible-ci/files/templated_contexts/moodle_nginx/conf/usr/libexec/check-container-nginx-moodle
- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/check-container-php-moodle
- .ansible-ci/files/templated_contexts/pgbouncer/conf/usr/libexec/check-container-pgbouncer
- .ansible-ci/files/templated_contexts/postgres/conf/usr/libexec/check-container-postgres
- .lighthouse/jenkins-x/release.yaml
> refactor(moodle): adjust probes

- .ansible-ci/inventory/group_vars/all/dockerfile_builder.yml
> chore(keydb): bump pkg version

- .ansible-ci/files/templated_contexts/node-ci/Dockerfile.j2
> feat(node): add procps-ng pkg

- .ansible-ci/files/templated_contexts/node-ci/Dockerfile.j2
> fix(node): clear npm cache

- .ansible-ci/files/templated_contexts/node-ci/Dockerfile.j2
> feat(node-ci): add check dep packages

- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/ansible-operator-ci/Dockerfile.j2
- .ansible-ci/inventory/host_vars/moodle41/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle41_kio/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/moodle41_nginx120_php80-fpm/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/nginx120_php80-fpm/dockerfile_builder.yml
- .ansible-ci/requirements.txt
- .ansible-ci/tasks/builder/cache.yml
- .ansible-ci/tasks/builder/tag.yml
- .ansible-ci/tasks/config/docker.yml
- .ansible-ci/tasks/pipeline/skip-ci.yml
- .ansible-ci/tasks/prepare/minimal.yml
- .lighthouse/jenkins-x/pullrequest.yaml
> ci: add python requirement

- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/files/templated_contexts/ansible/Dockerfile.j2
- .ansible-ci/inventory/group_vars/ci_grp/dockerfile_builder.yml
- .ansible-ci/requirements.yml
- .lighthouse/jenkins-x/pullrequest.yaml
> fix(ci): add ansible collections

- .ansible-ci/files/templated_contexts/ansible-docker-ci/Dockerfile.j2
- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/ansible-podman-ci/dockerfile_builder.yml
- .ansible-ci/inventory/host_vars/ansible/dockerfile_builder.yml
> feat(ci): bump kubectl version to 1.29

- .ansible-ci/files/templated_contexts/ansible-operator-ci/Dockerfile.j2
- .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
- .ansible-ci/templates/CTR-REPO-README.md.j2
- .ansible-ci/templates/README.md.j2
> feat(ansible-operator-ci): add tooling

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/bin/container-setup-php-moodle
> fix(moodle): install nc

- .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/usr/libexec/moodle/install-plugin-list
- moodle/moodle41/conf/usr/libexec/moodle/install-plugin-list
- moodle/moodle41_kio/conf/usr/libexec/moodle/install-plugin-list
- moodle/moodle41_php80-fpm/conf/usr/libexec/moodle/install-plugin-list
**Checklist:**
https://github.com/krestomatio/container_builder/issues/144
N/A
> fix(moodle): support tiny plugins

- .ansible-ci/build-with-multiarch-builder.yml
- .ansible-ci/build.yml
- .ansible-ci/hosts-to-json.yml
- .ansible-ci/inventory/host_vars/postgres13/dockerfile_builder.yml
- .ansible-ci/multiarch-builder.yml
- .ansible-ci/release.yml
> fix(postgres): use rocky8 for previous postgres bin
